stages:
  - build
  - notify

variables:
  MAVEN_OPTS: "-DskipTests"

build-backend-code-job:
  stage: build
  image: maven:3.8.11-openjdk-16
  only:
    changes:
      - backend/**/*    # запускать только если менялся бэкенд
  script:
    - cd backend
    - mvn -B package
  artifacts:
    name: "backend-$CI_COMMIT_SHORT_SHA"
    paths:
      - backend/target/*.jar
    expire_in: 1 week
    when: always

telegram-notification-backend:
  stage: notify
  image: curlimages/curl:8.10.1
  needs: ["build-backend-code-job"]   # дождаться сборки
  only:
    changes:
      - backend/**/*                  # AND: изменения в backend
    variables:
      - $CI_COMMIT_MESSAGE =~ /send notification/i   # AND: фраза в сообщении коммита
  script:
    - |
      ARTIFACT_URL="$CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_SHA/download?job=build-backend-code-job"
      MSG="✅ *Backend build success*\nProject: *$CI_PROJECT_PATH*\nBranch: *$CI_COMMIT_REF_NAME*\nCommit: \`$CI_COMMIT_SHORT_SHA\`\nArtifacts: $ARTIFACT_URL"
      curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
        -d chat_id="$TELEGRAM_CHAT_ID" \
        -d parse_mode=Markdown \
        --data-urlencode text="$MSG"
